public class Empresa {
	@AuraEnabled
    @InvocableVariable public String nome;
    @AuraEnabled
    @InvocableVariable public String abertura;
	@AuraEnabled
    @InvocableVariable public String situacao;
    @AuraEnabled
    @InvocableVariable public String tipo;
    @AuraEnabled
    @InvocableVariable public String fantasia;
    @AuraEnabled
    @InvocableVariable public String natureza_juridica;
    @AuraEnabled
    @InvocableVariable public String numero;
    @AuraEnabled
    @InvocableVariable public String municipio;
    @AuraEnabled
    @InvocableVariable public String bairro;
    @AuraEnabled
    @InvocableVariable public String uf;
    @AuraEnabled
    @InvocableVariable public String email;
    @AuraEnabled
    @InvocableVariable public String telefone;
    @AuraEnabled
    @InvocableVariable public String cnpj;
    @AuraEnabled
    @InvocableVariable public string status;
}