public class Empresa {

    @InvocableVariable public String abertura;

    @InvocableVariable public String situacao;
    
    @InvocableVariable public String tipo;
    
    @InvocableVariable public String fantasia;
    
    @InvocableVariable public String natureza_juridica;
    
    @InvocableVariable public String numero;
    
    @InvocableVariable public String municipio;
    
    @InvocableVariable public String bairro;
    
    @InvocableVariable public String uf;
    
    @InvocableVariable public String email;
    
    @InvocableVariable public String telefone;
    
    @InvocableVariable public String cnpj;
    
    @InvocableVariable public string status;
}